### ISSUE TITLE
Subwoofer distance calculation question

### ISSUE THREAD

**Issue by DeF-ault** [ObsessiveCompulsiveAudiophile/AudysseyOne#14]
Hi there,

first of all: Thank you very much for your great work!! Really impressive!

I did some tests with an existing measurement where subwoofer distance was 4.52 meters. The script changed it to SW1: 9.19m which is out of Denons range. The script recognizes it and optimizes it:
10:29:24 [WARNING] Calculated optimal subwoofer distance of 9.19m exceeds AV Receiver's max. speaker spacing limit [6.82m vs 6.00m]!
10:29:24 [INFO] Attempting to re-align the sub...
10:29:25 [INFO] Subwoofer distance is re-set to 8.03m and is now within receiver speaker spacing limits [5.66m vs 6.00m].

I'm now asking myself, if 8.03 is correctly determined as it is more than 5.66/6.00 m. 

I would be great, if you can have a look into this. Find attached my original ADY file and script log output:
[A1_optimization_log.txt
[20240120-evo-original.json.zip](https://github.com/ObsessiveCompulsiveAudiophile/AudysseyOne/files/14903152/20240120-evo-original.json.zip)
](https://github.com/ObsessiveCompulsiveAudiophile/AudysseyOne/files/14903144/A1_optimization_log.txt)

Thanks a lot and have a great day!!

Best,
Dennis

**Comment by MrDuderino2U** [comment]
Physical distance of your subwoofer(s) is somewhat irrelevant as you can incur much delay through the signal chain to the sub such as from DSP. You are fine with that, and mostly expected for it not to match perfect physical distance, but you can double check in REW to see. This might be the point where phase integration is best etc.

**Comment by DeF-ault** [comment]
Hi @MrDuderino2U ! Thank you for clarification! :-) Makes sense... I was just wondering as my understanding was that Denons max distance for subs can be set to 6.00 meters... But it sounds great, so I shouldn't care... :-) Cheers

**Comment by DeF-ault** [comment]
Hi @MrDuderino2U ! Thank you for clarification! :-) Makes sense... I was just wondering as my understanding was that Denons max distance for subs can be set to 6.00 meters... But it sounds great, so I shouldn't care... :-) Cheers
