### ISSUE TITLE
'Speaker names have different numbers of indices.' error with Denon X3800 and Directional subwooferMode

### ISSUE THREAD

**Issue by reedbotwright** [ObsessiveCompulsiveAudiophile/AudysseyOne#6]
Helping a user with a Denon X3800 and an ADY file from a 4-sub "directional" calibration. The config is 7.4.4 with 120 measurements generated out of the ADY for entry into REW (15 speakers times 8 positions). When running the optimization, get the error: "Speaker names have different numbers of indices." Not sure why.
[7.4.4-DIRECTIONAL-BASS.zip](https://github.com/ObsessiveCompulsiveAudiophile/AudysseyOne/files/14767130/7.4.4-DIRECTIONAL-BASS.zip)

**Comment by ObsessiveCompulsiveAudiophile** [comment]
A-1 will not work with 2 subs working in "directional bass" mode.

**Comment by reedbotwright** [comment]
Good to know! Is this a planned improvement in the future?

By the way, you rock! If you need any help with this project, please let me know.
